# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [ push ]
 
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: NPM Install and Build
        run: |
          npm install
          npm run build

  test:
    runs-on: ${{ matrix.os }}
  
    strategy:
      matrix:
        node-version: [12.x, 14.x]
        os:
          - ubuntu-latest
          - windows-latest
          
          
    name: Testing on Node ${{ matrix.node-version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: NPM Install and Test
        run: |
          npm install
          npm test
        env: 
          CI: true 
